### ISSUE TITLE
How do I download a video using this library?

### ISSUE THREAD

**Issue by SakthiMahendran** [rohit-chouhan/youtube-flutter#1]
In in the description it is mentioned that we can download video using this library. 
but there is no example showing how to do it. and it also seems that there is no functionality supporting this in the library.
Please make it clear.

Thank you : ).

**Comment by busslina** [comment]
1 commit, two small files, ... Seems that is not done yet

**Comment by rohit-chouhan** [comment]
youtube 2.0.0 is release with new methods, download option you will get in 2.0.1
