### ISSUE TITLE
Limitation??

### ISSUE THREAD

**Issue by Raghavan2005** [rohit-chouhan/youtube-flutter#3]
Hey, I can see that you're using HostGator for your domain. Do you have a YouTube API server running on your backend? If I'm going to use this in my application, I need to know about its maintenance and associated costs.

**Comment by rohit-chouhan** [comment]
Currently, this package is in its beta version, so the API is open. However, I plan to restrict the API in the future. If you would like to continue using our API, we will make it available on RapidAPI. You can access it from there.

**Comment by Raghavan2005** [comment]
Better you may implement Data Scraping
From https://www.youtube.com/watch?v=${videoId}
No api key required 
No limitation 
Runs on-device

**Comment by rohit-chouhan** [comment]
Thank you for the suggestion
